name: 'Setup Docker MacOS'
description: 'Sets up docker via docker-machine, and docker-compose on MacOS'
runs:
  using: "composite"
  steps:
    # https://github.com/docker/for-mac/issues/2359#issuecomment-943131345
    - shell: bash
      run: |
        brew install --cask docker
        
        echo "Installing Docker.app (unattended)..."
        sudo /Applications/Docker.app/Contents/MacOS/Docker --unattended --install-privileged-components
        
        echo "Starting docker daemon..."
        open -a /Applications/Docker.app --args --unattended --accept-license
        
        echo "Awaiting docker daemon..."
        while ! /Applications/Docker.app/Contents/Resources/bin/docker info &>/dev/null; do sleep 1; done
