name: 'Setup Docker MacOS'
description: 'Sets up docker via docker-machine, and docker-compose on MacOS'
runs:
  using: "composite"
  steps:
    # https://github.com/docker/roadmap/issues/80#issuecomment-633613240
    - shell: bash
      run: |
        echo "Installing Docker & Docker Compose CLI clients..."
        brew install docker docker-compose
        
        echo "Installing Docker Desktop..."
        # allow the app to run without confirmation
        xattr -d -r com.apple.quarantine /Applications/Docker.app
        # preemptively do docker.app's setup to avoid any gui prompts
        sudo /bin/cp /Applications/Docker.app/Contents/Library/LaunchServices/com.docker.vmnetd /Library/PrivilegedHelperTools
        sudo /bin/cp /Applications/Docker.app/Contents/Resources/com.docker.vmnetd.plist /Library/LaunchDaemons/
        sudo /bin/chmod 544 /Library/PrivilegedHelperTools/com.docker.vmnetd
        sudo /bin/chmod 644 /Library/LaunchDaemons/com.docker.vmnetd.plist
        sudo /bin/launchctl load /Library/LaunchDaemons/com.docker.vmnetd.plist
        
        echo "-- Starting Docker.app, if necessary..."
        open -g -a Docker.app || exit
        
        # Wait for the server to start up, if applicable.
        i=0
        while ! docker system info &>/dev/null; do
        (( i++ == 0 )) && printf %s '-- Waiting for Docker to finish starting up...' || printf '.'
        sleep 1
        done
        (( i )) && printf '\n'
        
        echo "-- Docker is ready."
